[global]
developmentMode = false

[theme]

# Primary accent for interactive elements
primaryColor = '#00A36C'

# Background color for the main content area
backgroundColor = '#334353'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#097969'

# Color used for almost all text
textColor = '#FAFAFA'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"